/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ProjectOops;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author velmurugan
 */
public class Fifthpage extends javax.swing.JFrame {

    /**
     * Creates new form Fifthpage
     */
    public Fifthpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("CHOOSE THE LEVEL OF the pic puzzle GAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 1130, 80);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(119, 178, 21, 21);

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel2.setText("EASY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(146, 166, 136, 48);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(177, 270, 21, 21);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel3.setText("MEDIUM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(204, 254, 160, 48);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(273, 342, 21, 21);

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel4.setText("HARD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 329, 116, 48);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(355, 428, 21, 21);

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel5.setText("TOUGH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(382, 412, 140, 48);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(480, 503, 21, 21);

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel6.setText("DIFFICULT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(501, 491, 201, 48);

        jButton1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(598, 557, 197, 126);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\F1.JPEG")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -460, 1310, 1730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            if(jRadioButton1.isEnabled())
            {
                 jRadioButton2.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                 jRadioButton2.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                new Pic3().setVisible(true);
               
            }
        }
         if(jRadioButton2.isSelected())
        {
            if(jRadioButton2.isEnabled())
            {
                 jRadioButton1.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                 jRadioButton1.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                new Pic4().setVisible(true);
               
            }
        }
           if(jRadioButton3.isSelected())
        {
            if(jRadioButton3.isEnabled())
            {
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
               jRadioButton1.setEnabled(false);
                jRadioButton2.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                new Pic5().setVisible(true);
                
            }
        }
            if(jRadioButton4.isSelected())
        {
            if(jRadioButton4.isEnabled())
            {
                  jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                  jRadioButton1.setEnabled(false);
                jRadioButton2.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                new Pic6().setVisible(true);
               
            }
        }
             if(jRadioButton5.isSelected())
        {
            if(jRadioButton5.isEnabled())
            {
                  jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton3.setSelected(false);
                  jRadioButton1.setEnabled(false);
                jRadioButton2.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton3.setEnabled(false);
                new Pic7().setVisible(true);
               
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fifthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fifthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fifthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fifthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fifthpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
