/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectOops;
/**
 *
 * @author velmurugan
 */
public class Sixthpage extends javax.swing.JFrame {

    /**
     * Creates new form Sixthpage
     */
    public Sixthpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setText("CHOOSE YOUR LEVEL FOR NUMBER PUZZLE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(55, 50, 1060, 64);

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel2.setText("EASY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(142, 172, 128, 48);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel3.setText("MEDIUM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(247, 266, 167, 48);

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel4.setText("HARD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(424, 359, 124, 48);

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel5.setText("TOUGH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(565, 449, 134, 48);

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel6.setText("DIFFICULT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(695, 538, 230, 48);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(115, 184, 21, 21);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(226, 278, 21, 21);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(403, 371, 21, 21);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(544, 463, 21, 21);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(674, 549, 21, 21);

        jButton1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 590, 350, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\SIXPAGE.JPEG")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 1290, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            if(jRadioButton1.isEnabled())
            {
                 jRadioButton2.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                 jRadioButton2.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                 new Num3().setVisible(true);
               
            }
        }
         if(jRadioButton2.isSelected())
        {
            if(jRadioButton2.isEnabled())
            {
                 jRadioButton1.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                 jRadioButton1.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                 new Num4().setVisible(true);
              
            }
        }
          if(jRadioButton3.isSelected())
        {
            if(jRadioButton3.isEnabled())
            {
                 jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton5.setSelected(false);
                 jRadioButton1.setEnabled(false);
                jRadioButton2.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton5.setEnabled(false);
                 new Num5().setVisible(true);
               
            }
        }
           if(jRadioButton4.isSelected())
        {
            if(jRadioButton4.isEnabled())
            {
                  jRadioButton1.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton5.setSelected(false);
                  jRadioButton1.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton2.setEnabled(false);
                jRadioButton5.setEnabled(false);
                 new Num6().setVisible(true);
             
            }
        }
            if(jRadioButton5.isSelected())
        {
            if(jRadioButton5.isEnabled())
            {
                 jRadioButton1.setSelected(false);
                jRadioButton3.setSelected(false);
                jRadioButton4.setSelected(false);
                jRadioButton2.setSelected(false);
                 jRadioButton1.setEnabled(false);
                jRadioButton3.setEnabled(false);
                jRadioButton4.setEnabled(false);
                jRadioButton2.setEnabled(false);
                 new Num7().setVisible(true);
             
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sixthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sixthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sixthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sixthpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sixthpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
